### ISSUE TITLE
avoiding caller exit errors

### ISSUE THREAD

**Issue by ruslandoga** [elixir-ecto/db_connection#269]
👋

When a caller starts a query and doesn't finish it before exiting, `db_connection` pool [terminates](https://github.com/elixir-ecto/db_connection/blob/bb311516b9b16731308d98f5fac07ec6c66b1322/lib/db_connection/watcher.ex#L39) the `db_connection` process.

```elixir
iex(37)> pid = spawn(fn -> Repo.query("select sleep(3)") end)
#PID<0.3079.0>

iex(38)> Process.exit(pid, :shutdown) # shutdown the spawned process within 3sec
true

iex(39)> [info] Clickhousex.Protocol (#PID<0.896.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.3079.0> exited
```

Would it be possible for `db_connection` to add an optional "cancel query" callback for adapters that support it? Stopping the process completely seems a bit suboptimal and noisy, but I understand the reasoning here as it's similar to linking and probably solves many edge cases.

**Comment by ruslandoga** [comment]
For context, this error gets logged when users switch between the [month `M`](https://plausible.io/plausible.io?period=month) and [year `Y`](https://plausible.io/plausible.io?period=year) periods on [https://plausible.io/plausible.io](plausible.io) faster than responses arrive.

**Comment by josevalim** [comment]
Yes, this is something we could do but note this is complicated because you may not know what was written on the socket when the query is aborted. For example, if you are in the middle of writing a query and aborts, then writing another query will leave you with mixed state. If you can guarantee this won't ever be the case for you, we could accept a PR that adds an optional callback that configures what happens in such cases (if such callback is not implemented, then we fallback to the current behaviour).

**Comment by ruslandoga** [comment]
@josevalim Thank you for the information! I'll try and explore if we can ensure no incomplete requests. And if I'm successful, I'll either reopen this issue or open a PR :)
