### ISSUE TITLE
DBConnection.prepare raises DBConnection.ConnectionError

### ISSUE THREAD

**Issue by hzamani** [elixir-ecto/db_connection#77]
Are `DBConnection.prepare/3` and `DBConnection.execute/4` expected to raise errors? If this is the case then why there are `prepare!/3` and `execute!/4` functions there?

**Comment by fishcakez** [comment]
The bang and non bang variants are for exceptions returned by a connection,
rather than by pool.

In Postgrex's case it will raise some of the connection exceptions on non
bang. Only errors from postgres are not raised when no bang, e.g.
constraint error. This occurs because postgres errors likely fit into
business logic but others do not, so likely do not want to handle in same
place.

**Comment by fishcakez** [comment]
The pool exceptions are now returned on master: https://github.com/elixir-ecto/db_connection/commit/53271f7d2636bafca3966bbee44d0ecf70d10064.
